version: 2
jobs:
  build:
    
    working_directory: ~/spring-rest-helloworld

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      
    steps:

      - checkout

      - restore_cache:
          key: spring-rest-helloworld-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/spring-rest-helloworld-0.0.1-SNAPSHOT.jar