version: 2
jobs:
  build:
    
    working_directory: ~/spring-rest-helloworld

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      
    steps:

      - checkout	  
	  - setup_remote_docker
	  
      - restore_cache:
          key: spring-rest-helloworld-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/spring-rest-helloworld-0.0.1-SNAPSHOT.jar
	  
      - run: 
          name: remove snapshot version
          command: |
            if mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -q "SNAPSHOT"; then mvn versions:set -DremoveSnapshot; fi;
            echo $(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)-$(echo $CIRCLE_SHA1 | cut -c -7)-$CIRCLE_BUILD_NUM > tempvers.txt
            mvn versions:set -DnewVersion=$(cat tempvers.txt) 

	  - run:
          name: Build application Docker image
          command: |
            cp target/*.war docker/app/
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --no-cache -t $CIRCLE_PROJECT_REPONAME:$(cat tempvers.txt) docker
            docker push $CIRCLE_PROJECT_REPONAME:$(cat tempvers.txt)
